### ISSUE TITLE
Set the URI for the base GeoJSON-LD context

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-ld#4]
The text is currently at https://github.com/geojson/geojson-ld/blob/master/geojson.jsonld.

When published at, e.g., http://example.com/contexts/geojson.jsonld it can be used in GeoJSON docs like this:

```
{ "@context": "http://example.com/contexts/geojson.jsonld",
  "type": "FeatureCollection", 
  "features": ...}
```

Once we arrive at a URI, I'll ask the GeoJSON authors to approve.

**Comment by mitar** [comment]
+1 for adding version number to context. So something like: `http://geojson.org/contexts/v1/geojson-base.jsonld`.

I would suggest though to drop the `.jsonld` extension. Why not just:

`http://geojson.org/contexts/v1/geojson-base`

Have you contacted GeoJSON working group? Are they open to publish it?

**Comment by mitar** [comment]
(BTW, why was this closed?)

**Comment by mitar** [comment]
The issue is that current file at http://geojson.org/contexts/geojson-base.jsonld still uses `example.com` URLs. This is then a bit useless, no? To have that context file already published?

Also, could http://geojson.org/contexts/geojson-base.jsonld have `id` and `type` be aliased to `@id` and `@type` in that context?
