### ISSUE TITLE
Register and configure a purl.org domain for indentifiers

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-ld#43]
As DCMI has done. This buffers applications from loss of the geojson.org domain. Following the instructions at https://www.w3.org/TR/swbp-vocab-pub/#purls.

**Comment by dret** [comment]
not sure this is a great move. it switches risk from losing your own domain to somebody else using theirs. imho, purl.org is as good idea as link shorteners in general, so not such a great idea. ymmv.

**Comment by akuckartz** [comment]
Thanks for attempting to reduce such risks. I am not certain that purl.org is optimal, but I currently can not offer a better alternative.

**Comment by elf-pavlik** [comment]
an alternative to purl.org - https://w3id.org/

**Comment by dret** [comment]
On 2016-11-27 19:16, elf Pavlik wrote:
> an alternative to purl.org - https://w3id.org/

sweet! a combo giving away your identity to a third party *and* a third 
party that creates the image of being associated with a well-known 
organization when it isn't...

**Comment by sgillies** [comment]
@dret purl.org is well established and I suspect it will outlive geojson.org. I'm not questioning Martin Daly's motives or stewardship at all, I'm just looking to register URIs with a proven service.

**Comment by mpdaly** [comment]
@sgillies That's me!

I'm more than happy to keep paying for the registration, but also more than happy to transfer it to any body that makes sense.

NB not **anybody**, but **any** **body**. I'd need a lot of convincing to transfer it to A. N. Other individual

**Comment by rybesh** [comment]
I would recommend taking a look at the California Digital Library's EZID service as an alternative to PURL: http://ezid.cdlib.org

PURL has had issues in the past, and while I'm encouraged that the new partnership with IA will help this, I still trust the CDL more (plus EZID is a better designed service IMO).

**Comment by rybesh** [comment]
There's a brief explanation of how we use EZID's Name-To-Thing resolver service to mint long-term URIs for PeriodO here: https://peerj.com/articles/cs-44/#p-39

**Comment by elf-pavlik** [comment]
```shell
$ whois w3id.org
Domain Name: W3ID.ORG
Domain ID: D167890068-LROR
WHOIS Server:
Referral URL: http://www.gandi.net
Updated Date: 2015-07-13T00:20:22Z
Creation Date: 2013-02-14T21:17:29Z
**Registry Expiry Date: 2024-02-14T21:17:29Z**
```

```shell
$ whois geojson.org
Domain Name: GEOJSON.ORG
Domain ID: D141206063-LROR
WHOIS Server:
Referral URL: http://www.dreamhost.com/
Updated Date: 2016-11-01T02:24:05Z
Creation Date: 2007-03-09T17:17:45Z
**Registry Expiry Date: 2017-03-09T17:17:45Z**
```

When deciding on *geojson.org* I suggest to right away register it for 10 years ahead.

**Comment by ekansa** [comment]
I agree with @rybesh about the persistent URI stuff. PURL is an OCLC project that's not very well supported and has less institutional commitment than I like. EZID is a good alternative.

Also, should the domain Geojson.org be owned by an appropriate nonprofit entity? I'm not sure who, maybe Mozilla? (Just to kick around an idea...)

**Comment by sgillies** [comment]
@ekansa @rybesh If you're willing to do the work, I'm fine with EZID. If it's up to me, I'm going with purl.org. Other to-big-to-fail vocabs are there, it's a [documented best practice](https://www.w3.org/TR/swbp-vocab-pub/#purls), and I know how it works.

**Comment by dr-shorthair** [comment]
It maybe depends what kinds of things you want persistent identifiers for. EZID is essentially a gateway to DOI and datacite, so it's primarily used for articles, reports,  datasets, and sometimes for real things like samples. It's not been generally used for "linked data"  type things. I believe you also need to have some kind of organizational arrangement or status to get access, which includes a long term commitment to maintaining the mappings (it is a gateway to DOI after all). So might not suit the applications you have in mind. 

I understand that the purl.org woes of the last 18 months are now over, or at least that purl.org is now in the hands of an organisation that cares. I would choose purl.org.

**Comment by rybesh** [comment]
What we're discussing are "name mapping authorities," of which purl.org is just one. The EZID name mapping authority is called [n2t](https://wiki.ucop.edu/display/Curation/N2T).

There are a couple of things to consider when choosing a name mapping authority:

1. Is it a single point of failure? purl.org certainly was under OCLC. Hopefully the IA will have the sense to enter into peering agreements with other NMAs; OCLC never did. n2t was designed from the beginning to be decentralized and replicated across multiple cultural heritage organizations.

2. How is it funded? If I had to guess, I would say that the IA will run out of money before the UC system does. IA is a non-profit relying on charity support; UC has a large permanent endowment.

That said, IA has really cleaned up and fixed purl.org since taking it over, and their management tools are better than what EZID currently offers for n2t. And it's true that many other "too big to fail" vocabs use purl.org (although that didn't stop purl.org from [failing pretty hard](https://groups.google.com/forum/#!topic/persistenturls/Zpd4BHQxxIM) for a while). Plus, if someone wanted to DDOS the semantic web, it would be more convenient for them to only have one domain to take out. 😃 

Anyway, in this case I agree that ease-of-management probably is more important than uptime and persistence. So, purl.org is probably OK in this case.

**Comment by dr-shorthair** [comment]
> if someone wanted to DDOS the semantic web

... it might imply a degree of relevance for and interest in the semantic web which it hasn't obviously achieved until now ;-)

**Comment by sgillies** [comment]
I deleted a comment. Let's stay on topic here.

**Comment by sgillies** [comment]
I wrote a very basic RDF schema, based on https://github.com/ewilderj/doap/blob/master/schema/doap.rdf, to go along with the HTML description of the vocab and added two new pages to the [GeoJSON GitHub pages project](https://github.com/geojson/geojson.github.io).

* http://geojson.org/ld/vocab.html
* http://geojson.org/ld/vocab.rdf

Next I've added two PURL records

![untitled](https://cloud.githubusercontent.com/assets/33697/21568128/37b692e8-ceb2-11e6-9590-4f519f84e268.png)

So that URIs like https://purl.org/geojson/vocab#Feature resolve to the RDF and we have a PURL for the GeoJSON JSON-LD @context document.

**Comment by sgillies** [comment]
Summary: the GeoJSON JSON-LD document references classes and properties from the `https://purl.org/geojson/vocab#` namespace. This namespace is defined by a single RDF/XML file, http://geojson.org/geojson-ld/vocab.rdf. The source for that file is in the gh-pages branch of this repository.
